/** Mapa de permisos por rol (espejo de `backend/src/core/security/role-permissions.ts`). */
export const ROLE_PERMISSIONS = {
  ADMIN: [
    'users:read',
    'users:write',
    'departments:read',
    'departments:write',
    'teams:read',
    'teams:write',
    'projects:read',
    'projects:write',
    'boards:read',
    'boards:write',
    'tasks:read',
    'tasks:write',
    'tasks:assign',
    'comments:write',
    'attachments:write',
    'notifications:read',
    'dashboard:read',
    'reports:read',
    'reports:export',
    'activity:read',
    'assets:read',
    'assets:write',
    'organizations:read',
    'organizations:write',
  ],
  MANAGER: [
    'users:read',
    'departments:read',
    'teams:read',
    'teams:write',
    'projects:read',
    'projects:write',
    'boards:read',
    'boards:write',
    'tasks:read',
    'tasks:write',
    'tasks:assign',
    'comments:write',
    'attachments:write',
    'notifications:read',
    'dashboard:read',
    'reports:read',
    'reports:export',
    'activity:read',
    'assets:read',
    'assets:write',
    'organizations:read',
    'organizations:write',
  ],
  WORKER: [
    'departments:read',
    'teams:read',
    'projects:read',
    'boards:read',
    'tasks:read',
    'tasks:write',
    'comments:write',
    'attachments:write',
    'notifications:read',
    'dashboard:read',
    'activity:read',
    'assets:read',
    'assets:write',
    'organizations:read',
  ],
  INSPECTOR: [
    'departments:read',
    'projects:read',
    'boards:read',
    'tasks:read',
    'tasks:write',
    'comments:write',
    'attachments:write',
    'notifications:read',
    'dashboard:read',
    'reports:read',
    'reports:export',
    'activity:read',
    'assets:read',
    'assets:write',
    'organizations:read',
  ],
  VIEWER: [
    'departments:read',
    'projects:read',
    'boards:read',
    'tasks:read',
    'notifications:read',
    'dashboard:read',
    'reports:read',
    'activity:read',
    'assets:read',
    'organizations:read',
  ],
} as const;

export type RoleNameKey = keyof typeof ROLE_PERMISSIONS;

export function roleHasPermission(
  role: RoleNameKey | string | undefined,
  permission: string,
): boolean {
  if (!role || !(role in ROLE_PERMISSIONS)) {
    return false;
  }
  return (ROLE_PERMISSIONS[role as RoleNameKey] as readonly string[]).includes(permission);
}

export const ALL_PERMISSIONS = [
  ...new Set(Object.values(ROLE_PERMISSIONS).flat()),
].sort() as string[];
